### ISSUE TITLE
README needs an update

### ISSUE THREAD

**Issue by junghans** [losalamos/flecsi-third-party#14]
The README needs an update on how to use `USE_SYSTEM_LIBS=ON/OFF` (after you tested it).

We might also want to mention docker:
```
docker pull laristra/flesci-third-party:fedora
docker run -it laristra/flesci-third-party:fedora /bin/bash
```

**Comment by junghans** [comment]
Also see
https://github.com/laristra/flecsi-buildenv/blob/master/fedora
and
https://github.com/laristra/flecsi-buildenv/blob/master/ubuntu
for recent `dnf` and `apt-get` package lists.

**Comment by junghans** [comment]
Related to #272.

**Comment by ktsai7** [comment]
@junghans 
- Is adding docker command into the third-party README for if someone wants to pull the third-party container to use it themselves?
- Is mentioning `dnf` and `apt-get` here instead of in buildenv README similar reason?

**Comment by junghans** [comment]
Yes, it should be used by developers so get a working environment. 

For the `dnf` and `apt-get` I would just link the line in the Dockerfile of `flecsi-buildenv`.
