### ISSUE TITLE
Drop unused libraries

### ISSUE THREAD

**Issue by junghans** [losalamos/flecsi-third-party#20]
I will drop libraries, which aren't used anymore:

- cereal
- thrust

@charest: what about

- scotch
- exodus

**Comment by junghans** [comment]
cereal and thrust done in #27.

**Comment by junghans** [comment]
@charest: Nothing in flecsi, flecsi-sp and flecsale depend on lapacke anymore, so let's drop that, too?

**Comment by charest** [comment]
go ahead and remove it

**Comment by junghans** [comment]
lapacke done in #30
