### ISSUE TITLE
CMake fails when no CMAKE_BUILD_TYPE is provided.

### ISSUE THREAD

**Issue by charest** [losalamos/flecsi-third-party#22]
Looks like when you don't specify a CMAKE_BUILD_TYPE, the build fails.  It gets most of the way through, but some of the libraries fail (see below).  Should we just force a default @junghans ?

[ 98%] Performing build step for 'scotch'
CMake Error at /home/charest/code/flecsi-third-party/build/scotch-prefix/src/scotch-stamp/scotch-build-.cmake:16 (message):
  Command failed: 2

   'make'

  See also

    /home/charest/code/flecsi-third-party/build/scotch-prefix/src/scotch-stamp/scotch-build-*.log

**Comment by junghans** [comment]
Can you post the end of `/home/charest/code/flecsi-third-party/build/scotch-prefix/src/scotch-stamp/scotch-build-*.log` ? My guess is that your gcc is too new to compile scotch.

**Comment by charest** [comment]
See attached.  

I don't think its a gcc version issue because `cmake -DCMAKE_BUILD_TYPE=Release ... && make` works.  But `cmake ... && make` does not.

[scotch-build.zip](https://github.com/laristra/flecsi-third-party/files/728098/scotch-build.zip)

**Comment by junghans** [comment]
```
/home/charest/code/flecsi-third-party/build/scotch-prefix/src/scotch/src/esmumps/dof.c:152:50: error: ‘NULL’ undeclared (first use in this function)
   SCOTCH_graphData (grafptr, &baseval, &vertnbr, NULL, NULL, &velotab, NULL, &edgenbr, NULL, NULL);
```
I have seen that before!

**Comment by charest** [comment]
`cmake -DCMAKE_BUILD_TYPE=Release ... && make` works too.

**Comment by junghans** [comment]
Hmm https://travis-ci.org/laristra/flecsi-third-party/jobs/194979870 seems to work too!

**Comment by charest** [comment]
Sorry I meant `cmake -DCMAKE_BUILD_TYPE=Debug ... && make` works too.  

The travis build works because `CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}` is specified on line 327 of the travis output.

**Comment by junghans** [comment]
But it is unset for most of the builds, so does `make -DCMAKE_BUILD_TYPE= .. && make` work?

**Comment by charest** [comment]
Yes, `cmake -DCMAKE_BUILD_TYPE= ... && make` works too.  Weird.

**Comment by junghans** [comment]
Even works without 9eaa261ba1c855e96847c84fca1231cd543eb127, build here: https://travis-ci.org/laristra/flecsi-third-party/jobs/195282012

**Comment by charest** [comment]
Then I don't know what to say.  Close it?

**Comment by junghans** [comment]
When did it fail for you?

**Comment by charest** [comment]
See original comment.

**Comment by junghans** [comment]
One more idea, from your log:
```
/home/charest/code/flecsi-third-party/build/install/include/common.h:29:1: error: expected specifier-qualifier-list before ‘public’
 public:
 ^~~~~~
```
is that the `common.h` from an earlier legion install? If so, you got fit by StanfordLegion/legion#172 and to need to clean out your install prefix before building scotch.

**Comment by charest** [comment]
It is the building of scotch I was having a problem with. But now the build seems to be working.  I suspect maybe its an issue with parallel builds, i.e. `make -j`.  Should I close it?

**Comment by junghans** [comment]
Yeah, the problem is that one has to build scotch before legion and have no legion already installed.

**Comment by charest** [comment]
Does the legion build depend on scotch?
