### ISSUE TITLE
language/src/rdir mucked about

### ISSUE THREAD

**Issue by jpietarilagraham** [losalamos/flecsi-third-party#31]
When I cd into legion; git co -b master origin/master; and try to build again I get this error:

[ 93%] Performing build step for 'legion'
CMake Error at /home/jgraham/github/broken-third-party/build/legion-prefix/src/legion-stamp/legion-build-Debug.cmake:16 (message):
  Command failed: 2

   'make'

git status shows that language/src/rdir is modified and I cannot make it unmodified, even if I check in the changes and rebase them out.

**Comment by ipdemes** [comment]
@jpietarilagraham , it that still the case? I see you put this issue on May 1st.

**Comment by jpietarilagraham** [comment]
No.  This has been fixed since May.
