### ISSUE TITLE
Create separate install target

### ISSUE THREAD

**Issue by jlippuner** [losalamos/flecsi-third-party#50]
If the install directory is deleted or modified after an initial build and install, one cannot simply re-install the built libraries since there is no install target. I had to run `make clean` and then rebuild everything in order to get it installed again. It would be nice to a have a separate install target so that one could simply run `make install` and the libraries would be installed without rebuilding them unnecessarily.

**Comment by junghans** [comment]
We are mis-using CMake’s `ExternalProject_Add()` to build the third party libraries and this function doesn’t have an easy way to separate the two rules! So this is not going to be a quick fix....
