### ISSUE TITLE
Updating Legion

### ISSUE THREAD

**Issue by ghost** [losalamos/flecsi-third-party#75]
Similar to issue #73 , Flecsi failed to build for me when I changed the runtime to Legion because of an error:
```
...cannot convert int to __vector(2)...
```
which I was able to immediately resolve by switching from the pinned commit that's here for Legion to their master branch. I'm building on a Power9 system with gcc 8.2.0 manually installed.

Cheers,
David

**Comment by ipdemes** [comment]
@dnicholaeff : Legion submodule has been updated today, could you, please, try again?

**Comment by ghost** [comment]
Danke.
